### PR TITLE
fix bug: ‘string’ does not name a type;

### PR DESCRIPTION
**Pull request by Higuoxing**
string is provided by std::string

or the building process will be failed

### CODE REVIEW

**Comment by Higuoxing** [comment]
Well, this is the whole information ...

```shell
In file included from <command-line>:0:0:
/home/me/Documents/WorkSpace/riscv-sodor/emulator/common/verilator.h:15:19: error: ‘string’ does not name a type; did you mean ‘stdin’?
   bool open(const string& name) override {
                   ^~~~~~
                   stdin
/home/me/Documents/WorkSpace/riscv-sodor/emulator/common/verilator.h:15:8: error: ‘bool VerilatedVcdFILE::open(const int&)’ marked ‘override’, but does not override
   bool open(const string& name) override {
        ^~~~
make[2]: *** [VTop.mk:63: emulator.o] Error 1
make[2]: Leaving directory '/home/me/Documents/WorkSpace/riscv-sodor/emulator/rv32_1stage/obj_dir'
make[1]: *** [/home/me/Documents/WorkSpace/riscv-sodor/emulator/common/Makefile.include:104: emulator] Error 2
make[1]: Leaving directory '/home/me/Documents/WorkSpace/riscv-sodor/emulator/rv32_1stage'
make: *** [Makefile:108: emulator/rv32_1stage/emulator] Error 2
```

**Comment by redpanda3** [comment]
Thank you. I have the same issue.

**Comment by Higuoxing** [comment]
> Thank you. I have the same issue.

Hi, you could use [librecores/riscv-sodor](https://github.com/librecores/riscv-sodor), these bugs are fixed there : )

**Comment by edwardcwang** [comment]
Fixed by #42

**Pull request closed without merging**
